--- 
site: bookdown::bookdown_site
output:
  bookdown::pdf_book:
    includes:
      in_header: preamble.tex
      before_body: pref.tex
      after_body: after.tex
    keep_tex: yes
    citation_package: biblatex
documentclass: isuthesis
classoption:
  - notitlepage
fontsize: 12pt
# bibliography: masterbib.bib
# biblio-style: apa
# nocite: '@*'
# biblatexoptions: [refsegment=chapter]
# biblatexoptions: [refsection=chapter, backref=false]
# , hyperref=true, backref=FALSE, backend=biber, 
#   bibencoding=utf8]
  # , style=authoryear, natbib=true, style=numeric-comp]
toc: False
# link-citations: yes
---

<!-- # biblatexoptions: [refsegment=chapter] -->

<!--  backref=true, style=authoryear, natbib=true, style=numeric-comp] -->

```{r echo=FALSE}
Sys.setenv(RSTUDIO_PDFLATEX = "latexmk")
```

```{r setup, include = FALSE}
# Global R options
options(
  digits = 3,
  dplyr.print_min = 6, 
  dplyr.print_max = 6, 
  htmltools.dir.version = FALSE,
  width = 70
)

# R markdown options
knitr::opts_chunk$set(
  cache = FALSE,
  comment = "#>",
  collapse = TRUE,
  dpi = 500,
  echo = FALSE,
  error = FALSE,
  fig.align = "center",
  fig.keep = 'high',
  fig.pos = 'tbp!',
  message = FALSE,
  warning = FALSE
)
  
# Other options
knitr::opts_knit$set(eval.after = "fig.cap")




```


