\refsection
\chapter{GENERAL INTRODUCTION}

\label{general_intro}

This chapter will have the introduction to your thesis as a whole.

This is the opening paragraph to my thesis which
explains in general terms the concepts and hypothesis
which will be used in my thesis.

With more general information given here than really
necessary.

\begin{figure}[h!tb] \centering
```{r echo=FALSE}
plot(iris$Sepal.Length)
```

\isucaption{Example of Rmarkdown based code chunk that includes R code}
\label{code_figure}
\end{figure}

\section{Overview}

Here initial concepts and conditions are explained and
several hypothesis are mentioned in brief. Figure \ref{code_figure} is an example of R code chunk generating a figure.

\subsection{Hypothesis}

Here one particular hypothesis is explained in depth
and is examined in the light of current literature.

\subsubsection{Parts of the hypothesis}

Here one particular part of the hypothesis that is 
currently being explained is examined and particular
elements of that part are given careful scrutiny.

<!-- Below \subsubsection -->
<!-- Sectional commands: \paragraph and \subparagraph may also be used -->

\subsection{Second Hypothesis}

Here one particular hypothesis is explained in depth
and is examined in the light of current literature.

\subsubsection{Parts of the second hypothesis}

Here one particular part of the hypothesis that is 
currently being explained is examined and particular
elements of that part are given careful scrutiny
\cite{allen}, \cite{bruner}

<!-- \cite{prime-number-theorem} abcd.  -->

\section{Criteria Review}

Here certain criteria are explained thus eventually
leading to a foregone conclusion.

\section{References}
\printbibliography[heading=none, section=1]
\endrefsection



